name: Main Branch

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'  # Replace with the desired .NET Core version

      - name: Print working directory
        run: pwd
        
      - name: Restore dependencies
        run: dotnet restore ./Calculator_Demo/Calculator_Demo.sln

      - name: Build project
        run: dotnet build --configuration Release ./Calculator_Demo/Calculator_Demo.sln

      - name: Run tests
        run: dotnet test ./Calculator_Demo/Calculator_Demo.sln
