name: Main Branch
env:
    solution_file_location: ./Calculator_Demo/Calculator_Demo.sln
    testfile_csproj_location : ./Calculator_Demo/Calculator_Demo.Test/Calculator_Demo.Test.csproj
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'  # Replace with the desired .NET Core version

      - name: Check if unit test project exists
        id: check-project
        run: |
          if [ -f "$testfile_csproj_location" ]; then
            echo "::set-output name=exists::true"
            echo "Test file found"
          else
            echo "::set-output name=exists::false"
            echo "Test file not found"
          fi

      - name: Restore dependencies
        run: dotnet restore "$file_location"

      - name: Build project
        run: dotnet build --configuration Release "$file_location"
      - name: Run tests
        run: |
          if [ "${{ steps.check-project.outputs.exists }}" = "true" ]; then
            dotnet test --configuration Release "$file_location"
          else
            echo "Unit test project file not found. Skipping tests."
          fi
