name: Main Branch

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'  # Replace with the desired .NET Core version

      - name: Check if unit test project exists
        id: check-project
        run: |
          if [ -f "./UnitTestProject/UnitTestProject.csproj" ]; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run tests
        run: |
          if [ "${{ steps.check-project.outputs.exists }}" = "true" ]; then
            dotnet test --configuration Release --logger "trx;LogFileName=test_results.trx"
          else
            echo "Unit test project file not found. Skipping tests."
          fi
